export const txns = [
  {
    id: '001',
    amount: 400,
    category: 'Bills',
    subcategory: 'Rent',
    expenseAccount: 'SBI',
    incomeAccount: null,
    type: 'expense',
    note: `Both of useEffect and useLayoutEffect are used for performing side effects and return an optional cleanup function which means if they don't deal with returning values, no types are necessary. When using useEffect, take care not to return anything other than a`,
    date: '17 Dec',
  },
  {
    id: '002',
    amount: 500,
    category: 'Food',
    subcategory: null,
    expenseAccount: 'SBI',
    incomeAccount: null,
    type: 'expense',
    date: '17 Dec',
  },
  {
    id: '003',
    amount: 600,
    category: 'Studies',
    subcategory: 'Books',
    expenseAccount: 'SBI',
    incomeAccount: null,
    type: 'expense',
    date: '18 Dec',
  },
];
